In [ ]:
import numpy as np #librería para operaciones algebraicas y numéricas
import pandas as pd #librería para manejo de datos

#programo el método bisección
def biseccion(a, b , tol, itmax = 100): 
        df = pd.DataFrame(columns=('ai','bi','pi','cond','f_ai_f_pi'))
        a = a 
        b = b
        contador = 0  
        x0, x1 = a, b 
        if(f(a) * f(b)>0):         #condicion de aplicabilidad del método
            print( "El método no resuelve este tipo de raíz")
            return
        while (contador < itmax) and (abs((x1 - x0) / x1) > tol):
            x0 = x1                                                 
            x1 = (a + b)/2                      
            f_ai_f_pi = f(a) * f(x1)
            if f_ai_f_pi < 0:      
                df.loc[contador] = [a,b,(a+b)/2,'<0',f_ai_f_pi]
                b = x1
            else:
                df.loc[contador] = [a,b,(a+b)/2,'>0',f_ai_f_pi]
                a = x1
            contador += 1                      
        error = abs((x1 - x0) / x1)
        print('El método de bisección convergió en',contador,'iteraciones')
        return df

In [ ]:
#defino el intervalo de arranque y la tolerancia
A=2
B=6
pendiente_veriles = 4

tolerancia=10**(-5)

def f(y):
    # Constantes dadas por el enunciado [1]
    n = 0.025 
    b = 20
    S = 0.002
    z = pendiente_veriles 
    Q_real = 410
    
    # Fórmulas de la sección trapezoidal [2]
    A = (b + z*y)*y
    P = b + 2*y * ((1 + z**2)**0.5)
    R = A / P
    
    # Ecuación de Manning igualada a cero: Q_calc - Q_real = 0 [2]
    Q_calc = (1/n) * A * (R**(2/3)) * (S**0.5)
    return Q_calc - Q_real
#A la hora de probar un ejemplo, recueden que para aplicar estos dos métodos se debe cumplir:
# - que la función sea contínua en el intervalo
# - que exista una raíz en el intervalo y que sea única y con multiplicidad impar (si 'rebota', no puedo aplicar el método)

casp_z2=biseccion(A, B, tolerancia)

TypeError: f() missing 1 required positional argument: 'z'

In [ ]:
caso_z4.tail(10)

          ai        bi        pi cond  f_ai_f_pi
7   3.593750  3.625000  3.609375   >0   2.781948
8   3.609375  3.625000  3.617188   <0  -0.720230
9   3.609375  3.617188  3.613281   <0  -0.134808
10  3.609375  3.613281  3.611328   >0   0.157644
11  3.611328  3.613281  3.612305   >0   0.004008
12  3.612305  3.613281  3.612793   <0  -0.001568
13  3.612305  3.612793  3.612549   <0  -0.000639
14  3.612305  3.612549  3.612427   <0  -0.000174
15  3.612305  3.612427  3.612366   >0   0.000058
16  3.612366  3.612427  3.612396   <0  -0.000012

In [14]:
pendiente_veriles = 6
A=2
B=6
tolerancia=10**(-5)
def f(y):
    # Constantes dadas por el enunciado [1]
    n = 0.025 
    b = 20
    S = 0.002
    z = pendiente_veriles 
    Q_real = 410
    
    # Fórmulas de la sección trapezoidal [2]
    A = (b + z*y)*y
    P = b + 2*y * ((1 + z**2)**0.5)
    R = A / P
    
    # Ecuación de Manning igualada a cero: Q_calc - Q_real = 0 [2]
    Q_calc = (1/n) * A * (R**(2/3)) * (S**0.5)
    return Q_calc - Q_real
caso_z6=biseccion(A, B, tolerancia)
caso_z6.tail(10)

El método de bisección convergió en 17 iteraciones

          ai        bi        pi cond  f_ai_f_pi
7   3.343750  3.375000  3.359375   <0  -0.753398
8   3.343750  3.359375  3.351562   >0   6.507866
9   3.351562  3.359375  3.355469   >0   1.363071
10  3.355469  3.359375  3.357422   >0   0.222812
11  3.357422  3.359375  3.358398   >0   0.012020
12  3.358398  3.359375  3.358887   <0  -0.003378
13  3.358398  3.358887  3.358643   <0  -0.000811
14  3.358398  3.358643  3.358521   >0   0.000472
15  3.358521  3.358643  3.358582   <0  -0.000046
16  3.358521  3.358582  3.358551   >0   0.000041