![Curso Schwarz-Sosa-Suriano](http://www.fi.uba.ar/sites/default/files/logo.png)
# Diferenciación Numérica - Segunda parte
**Curso Schwarz - Sosa - Suriano**
- Métodos Numéricos. *Curso 2*
- Análisis Numérico I. *Curso 4*
- Métodos Matemáticos y Numéricos. *Curso 6*

**Problemas de la diferenciación numérica**
* Disminuir el paso puede traer problemas con el error de redondeo.
* No siempre es posible utilizar métodos de convergencia superior.

### Extrapolación de Richardson
Es un método que a partir de fórmulas de bajo orden, genera resultados de orden superior sin que sea necesario disminuir mucho el paso h. 
<br>Puede aplicarse cuando el método de aproximación puede expresarse de la forma: 

$$M = N(h) + E(h)$$

Siendo:<br>
* **M**: valor exacto
* **N(h)**: aproximación 
* **E(h)**: error 

Podemos ver que los métodos vistos para aproximar la derivada de una función se pueden expresar de esta manera.

El algoritmo cuando se utiliza la fórmula de diferencias progresivas, cuyo orden es lineal O(h), es el siguiente: 
$$N_j(h)=N_{j-1}(h/2)+\frac{N_{j-1}(h/2)-N_{j-1}(h)}{q^{j-1}-1}$$
$$q=2$$

**EJEMPLO**<br>
Para ver como se aplica este método vamos a continuar con el ejemplo de la primera parte: <br>
$$ f(x) = x^2 + 3x - exp(x)$$
$$f'(x0)$$
$$x_0=4$$

In [1]:
import numpy as np #librería para operaciones algebraicas y numéricas
import pandas as pd #librería para manejo de datos
import sympy as sp #librería para manejo simbólico de ecuaciones
import matplotlib.pyplot as plt
from IPython.display import display, Math
import sympy.printing as printing

In [2]:
#Primero trabajamos con la función simbólicamente para que calcule la derivada
x = sp.symbols('x')
y = x*x+3*x-sp.exp(x) #Acá hay que escribor la función a analizar

#Evalúar numéricamente la función
f=sp.lambdify(x,y)

In [13]:
#Derivada analítica
x0=4
yd = sp.diff(y,x) #Calcula la derivada simbólica
fd=sp.lambdify(x,yd)
derivada=fd(x0)

Como el método utiliza la fórmula de las diferencias progresivas, volvemos a definir el método.

In [4]:
#Método de diferencias progresivas
def DifProgresivas(x0,h):
    df=(f(x0+h)-f(x0))/h
    return df

In [5]:
#Definimos el error relativo
def ErrorRel(real,aprox):
    e=100*abs((aprox-real)/aprox)
    return e

In [6]:
n=3 #Cantidad de intervalos que vamos a utilizar
h=np.zeros(n) 
N=np.zeros((n,n))
Error=np.zeros((n,n))

In [7]:
x0=4 #Definimos el punto en que el queremos calcular f'(x0)
h[0]=0.5 #Definimos el paso inicial h0
print("Definimos el paso inicial h= ",h[0])
N[0][0]=DifProgresivas(x0,h[0]) #Aplicamos la formula de diferencias progresivas para h0 
Error[0][0]=ErrorRel(derivada,N[0][0])
print("Calculamos la primera aproximación con el método de diferencias progresivas en x0 =" ,x0, "tomando h =",h[0], "La llamamos N0(h)")
print("Cuando aplicamos este método obtenemos un resultado con un orden de convergencia lineal O(h)")

Definimos el paso inicial h=  0.5
Calculamos la primera aproximación con el método de diferencias progresivas en x0 = 4 tomando h = 0.5 La llamamos N0(h)
Cuando aplicamos este método obtenemos un resultado con un orden de convergencia lineal O(h)

In [8]:
for i in range(1,n):
    j=0
    h[i]=(h[i-1])/2
    print ("Aplicamos por "+str(i+1)+" vez la fórmula de diferencias progresivas con un paso h/"+str(2**i)+":")
    N[i][j]=DifProgresivas(x0,h[i])
    Error[i][j]=ErrorRel(derivada,N[i][j])
    print("Obtenemos N"+str(j)+"(h/"+str(2**i)+") = ",N[i][j],"con h/"+str(2**i)+"= ",h[i],"\n")
    for j in range(1,i+1):
        print("Aplicamos la fórmula de Richardson para j = "+str(j)+".")
        N[i][j]=N[i][j-1]+(N[i][j-1]-N[i-1][j-1])/((2**j)-1)
        Error[i][j]=ErrorRel(derivada,N[i][j])
        ec = "N_"+str(j)+"(h/"+str((2**i)/2)+") = N_"+str(j-1)+"(h/"+str(2**i)+")+\\frac{N_"+str(j-1)+"(h/"+str(2**i)+") - N_"+str(j-1)+"(h/"+str((2**i)/2)+")}{2^"+str(j)+"-1}"
        display(Math(printing.latex(ec,mul_symbol='dot')))
        print("N"+str(j)+"(h/"+str(i)+") = ",N[i][j],"\n")
        print("Obtenemos un resultado con un orden de convergencia O(h^"+str(j+1)+")\n")

Aplicamos por 2 vez la fórmula de diferencias progresivas con un paso h/2:
Obtenemos N0(h/2) =  -50.77904925417448 con h/2=  0.25

Aplicamos la fórmula de Richardson para j = 1.

N1(h/1) =  -42.22013597359381

Obtenemos un resultado con un orden de convergencia O(h^2)

Aplicamos por 3 vez la fórmula de diferencias progresivas con un paso h/4:
Obtenemos N0(h/4) =  -47.03227373778918 con h/4=  0.125

Aplicamos la fórmula de Richardson para j = 1.

N1(h/2) =  -43.285498221403884

Obtenemos un resultado con un orden de convergencia O(h^2)

Aplicamos la fórmula de Richardson para j = 2.

N2(h/2) =  -43.640618970673906

Obtenemos un resultado con un orden de convergencia O(h^3)

In [12]:
NT=np.transpose(N)
Resultados=pd.DataFrame({"h": h, "N0": NT[0],"N1":NT[1],"N2":NT[2]})
Resultados['N1'] = Resultados['N1'].replace(0, "-")
Resultados['N2'] = Resultados['N2'].replace(0, "-")
Resultados.head()

       h         N0       N1       N2
0  0.500 -59.337963        -        -
1  0.250 -50.779049 -42.2201        -
2  0.125 -47.032274 -43.2855 -43.6406

In [10]:
print('Derivada analítica en x =',x0, 'es',derivada)

Derivada analítica en x = 4 es -43.598150033144236

In [11]:
ErrorT=np.transpose(Error)
Error=pd.DataFrame({"h": h, "O(h)": ErrorT[0],"O(h^2)":ErrorT[1],"O(h^3)":ErrorT[2]})
Error['O(h^2)'] = Error['O(h^2)'].replace(0, "-")
Error['O(h^3)'] = Error['O(h^3)'].replace(0, "-")
Error.head()

       h       O(h)    O(h^2)     O(h^3)
0  0.500  26.525704         -          -
1  0.250  14.141461   3.26388          -
2  0.125   7.301632  0.722302  0.0973152

![Curso Schwarz-Sosa-Suriano](http://www.fi.uba.ar/sites/default/files/logo.png)



# Diferenciación Numérica




***

**Curso Schwarz - Sosa - Suriano**
- Métodos Numéricos. *Curso 2*
- Análisis Numérico I. *Curso 4*
- Métodos Matemáticos y Numéricos. *Curso 6*